### ISSUE TITLE
Example of code ?

### ISSUE THREAD

**Issue by diegoantognini** [gaetangate/text-summarizer#4]
Hi,

Thank you for sharing the code. I was wondering if it would be possible to have an example of a code to generate summaries, in a similar manner as in the paper.

Thank you in advance !

**Comment by ilyasst** [comment]
It would be great if we can have examples similar to the ones in the paper.

Thanks !

**Comment by Soe2Lwin** [comment]
hello,
Can I summarize Myanmar text with this code? Can I train with Myanmar(Burmese) news Corpus with word embedding to summarize Myanmar text.

**Comment by A-Gulati** [comment]
I'd really like an example on this as well!

**Comment by tlifcen** [comment]
Hello,
Would you like provide a demo to show the method of using the code? Is this code suitable for Chinese? What's the format of input data? @lambdaofgod

**Comment by lambdaofgod** [comment]
You can find usage examples in some of mine notebooks [on extractive summarization in general](https://github.com/lambdaofgod/examples-counterexamples/blob/dcde26141bc43a8762ef047b09e7e2107c77c274/notebooks/text_mining/Extractive_Summarization.ipynb) and on [CNN-Dailymail Extractive Summarization](https://github.com/lambdaofgod/examples-counterexamples/blob/578adbb59defb049305a0cddc127877934122c42/notebooks/text_mining/CNN-Dailymail%20Extractive%20Summarization.ipynb).

As for using different languages the preprocessing depends on NLTK, so it should be possible as NLTK supports your language's tokenizer (see [here](https://github.com/gaetangate/text-summarizer/blob/master/text_summarizer/base.py#L65))

**Comment by gaetangate** [comment]
The method is described in this step-by-step guide https://towardsdatascience.com/a-better-approach-to-text-summarization-d7139b571439

**Comment by Soe2Lwin** [comment]
thank you so much for sharing.
________________________________
